import type { Metadata } from "next";
import { Geist, Geist_Mono, Figtree } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Nav from "@/app/components/Nav";

const figtree = Figtree({subsets:['latin'],variable:'--font-sans'});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const safeAreaStyle = {
    paddingTop: "calc(env(safe-area-inset-top) + 30px)",
    paddingRight: "calc(env(safe-area-inset-right) + 12px)",
    paddingBottom: "calc(env(safe-area-inset-bottom) + 30px)",
    paddingLeft: "calc(env(safe-area-inset-left) + 12px)",
  };

  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", geistSans.variable, geistMono.variable, "font-sans", figtree.variable)}
    >
      <body className="min-h-screen bg-slate-950 flex items-center justify-center p-0 sm:p-6">
        <div
          className="relative w-full min-h-screen bg-white overflow-hidden flex flex-col sm:max-w-107.5 sm:min-h-215 sm:h-[90vh] sm:max-h-225 sm:rounded-[2.25rem] sm:border-10 sm:border-slate-800 sm:shadow-2xl"
          style={safeAreaStyle}
        >
         <main className="flex-1 no-scrollbar overflow-hidden overflow-y-scroll touch-pan-y overscroll-contain pb-24">
        {children}
        </main>
          <Nav/>
        </div>  
      </body>
    </html>
  );
}
